---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "nft-frontend"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nft-frontend"
  namespace: "nft-frontend"
  labels:
    app: "nft-frontend"
    proj: "nft-frontend"
    type: "frontend.react"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nft-frontend"
      proj: "nft-frontend"
      type: "frontend.react"
  template:
    metadata:
      labels:
        app: "nft-frontend"
        proj: "nft-frontend"
        type: "frontend.react"
    spec:
      containers:
      - name: "nft-frontend-sha256-1"
        image: "gcr.io/nft-platform-345404/github.com/vnggames/nft-frontend@sha256:274daf02a054d9eaa6c30c5aff0e57a2f59e49f25a740be73e5d1100608bfd64"
        readinessProbe:
          httpGet:
            port: 3000
            path: /
          initialDelaySeconds: 15
          periodSeconds: 15
      nodeSelector:
        cloud.google.com/gke-nodepool: compute

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nft-frontend-hpa-2y4e"
  namespace: "nft-frontend"
  labels:
    app: "nft-frontend"
    proj: "nft-frontend"
    type: "frontend.react"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nft-frontend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
---
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: nft-frontend-cert
  namespace: "nft-frontend"
spec:
  domains:
    - ciam.nft.rndengineer.org
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: nft-frontend-check
  namespace: "nft-frontend"
spec:
  healthCheck:
    checkIntervalSec: 15
    type: HTTP
    port: 3000
    requestPath: /
---
apiVersion: v1
kind: Service
metadata:
  name: nft-frontend
  namespace: "nft-frontend"
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "nft-frontend-check"}'
spec:
  selector:
    app: "nft-frontend"
    proj: "nft-frontend"
    type: "frontend.react"
  type: NodePort
  ports:
    - name: main
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: nft-frontend-fe
  namespace: "nft-frontend"
spec:
  redirectToHttps:
    enabled: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nft-frontend-managed-cert-ingress
  namespace: "nft-frontend"
  annotations:
    kubernetes.io/ingress.global-static-ip-name: nft-frontend
    networking.gke.io/managed-certificates: nft-frontend-cert
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: nft-frontend-fe
spec:
  defaultBackend:
    service:
      name: nft-frontend
      port:
        number: 3000
